Introducing checkqc
Molmed/snpseq_packs pull request #15
Opened 2018-01-29 15:11 UTC by MatildaAslin

**What problems does this PR solve?**
Replaces the sisyphus quickReport + QC check with checkQC.

**How has the changes been tested?**
New action tested locally with checkQC web service.  

**Reasons for careful code review**
If any of the boxes below are checked, extra careful code review should be inititated.

  - [ ] This PR contains code that could remove data

2018-01-30 07:24 UTC, johandahlberg requested changes
This looks great! I have added some small comments, mostly on syntax things.

2018-01-30 07:24 UTC, johandahlberg commented on actions/run_checkqc.py
> +        if (ignore_result & exit_status != 0):
The `&` operator in Python means [bitwise and](https://wiki.python.org/moin/BitwiseOperators), so this should be `and` here.

2018-01-30 07:24 UTC, johandahlberg commented on actions/run_checkqc.py
> +        elif (exit_status == 0):
No need for the parenthesis here.

2018-01-30 07:24 UTC, johandahlberg commented on actions/run_checkqc.yaml
> +name: get_response
I think that the name of this action should be `run_checkqc`, and then the name of the python script should probably be the same to make it easier to see which things belong together.

2018-01-30 07:24 UTC, johandahlberg commented on tests/test_run_checkqc.py
> +class runCheckQCTestCase(BaseActionTestCase):
Capital letter in the class name here: `RunCheckQCTestCase`

2018-01-30 07:24 UTC, johandahlberg commented on actions/run_checkqc.py
> +class runCheckQC(Action):
Capital letter in python class names: `RunCheckQC`

2018-01-30 15:06 UTC, monikaBrandt reviewed
Looks good! Good job!

2018-01-30 15:18 UTC, johandahlberg approved these changes

2018-01-30 15:18 UTC, MatildaAslin commented
@johandahlberg I've fixed your requested changes. 

@monikaBrandt @johandahlberg Thank you! We might wanna wait with merging until this branch has been validated.

2018-01-30 15:18 UTC, johandahlberg commented
Let us know when you want this merged @MatildaAslin .

2018-01-31 13:44 UTC, MatildaAslin commented
Validation complete! 🎉 Feel free to merge @monikaBrandt @johandahlberg

2018-01-31 13:45 UTC, johandahlberg commented
🍾 Great!

2018-01-31 13:45 UTC, merged