enable slack notifier to use a proxy
Molmed/snpseq_packs pull request #27
Opened 2018-07-24 14:36 UTC by slohse

**What problems does this PR solve?**
This PR allows configuring the `post_to_slack` action to use a proxy when connecting to the API hook.

**How has the changes been tested?**
Tested on the `testarteria-master` vagrant machine with a proxy running on `testgwy`

**Reasons for careful code review**
If any of the boxes below are checked, extra careful code review should be inititated.

  - [ ] This PR contains code that could remove data

2018-07-24 14:44 UTC, slohse commented
If I interpret the Travis error message correctly, it fails due to the renaming of the repo. Because it checks out to `snpseq-packs` but expects `arteria-packs`. This is not a problem on arteria-master, because the folder our ansible role checks out to is called `arteria-packs`.

2018-07-25 06:09 UTC, johandahlberg requested changes
I think that the problem with travis is that the pack name has not been changed in this file. https://github.com/Molmed/snpseq-packs/blob/master/pack.yaml Could you do that?

Great work!

2018-07-25 06:09 UTC, johandahlberg commented on actions/lib/slack.py
> +        if "slack_proxy_url" in self.config and self.config["slack_proxy_url"] != "":
I think a simpler formulation here might be to use `if self.config.get("slack_proxy_url")`?

2018-07-26 11:29 UTC, slohse commented
every single action and rule has a `pack` attribute, which is arteria-packs. Could it be that those are the problem?

2018-07-26 12:07 UTC, johandahlberg commented
Possibly yes. I'd search/replace them and see if that helps. Have you gotten the tests to pass locally?

2018-07-31 11:46 UTC, slohse commented
Alright, I rebased onto master (with the pack rename fixes) and now Travis is happy :)

2018-08-06 10:38 UTC, merged